language: python
python:
- '3.6'
- '3.7'
- '3.8'
install:
- pip install -e .
script:
- pytest
deploy:
  provider: pypi
  user: "__token__"
  password:
    secure: fqQELRdzI4Jx4p4WdFsDbfgv0yhyWuEEQ+udTRWnHcDuNR3YHTGR6jcORMKoRCxV3UqjvhKv5NQURLkhyugF2WxP6YynaCvCxdWfVgvPVawgHHLSOEomdlfj3Ezr3bqnF1xvSVKpK7JhHSkGO+3ZQkkr5m/cf9IygkMYCRPekHrhsNR1zE0Wt67o/nXXbP7vkhi5fkTE4K71yU5DVtJRsxsySKHVJwu8rWthNOInI5Gnj8RQXJfHcdp/Re8XW55YKZ3aeQuLe2zFTwK0+BT8GrxY0y+5T9jTDavE2TJz4kwwFdkFTpvaa9awkmiQm8kGaRIvGkAwzCR6gs2OziF5g273jKUKMyFYwYL6qwjRK7Hulrj6l3/ALbYaLBKzh8jcAJDYQWmR6jLtyfeASMczQZNJT4QT878Qh8M7JVDmqlGPPWispnNgOdkZlaDaoEVlz30Xgpqv7DSuOdhpPN0PszwRZAH9VtVmQfYDoXNTraFmh18WVxAUQlS1yqpd6HbJa5gpASRHUF6hETyPS6i4W5foyVaVXFNMH0TIAeOYnPkHjKGthx6PAVcfny74gZ4padg/U5sENI2lKPC4IE7UuvqwwK7LU4n/4djBJYm9Ap3ZA/FvbWYY1hepkysXGh+P8Rf/Rh2PBY76z1GWkBtEOlGo6+MoDDP6MwaN21YHEbk=
  on:
    tags: true
  skip_existing: true
